apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: azureresources.stable.gripdev.xyz
  finalizers:
  - finalizer.azureresources.stable.gripdev.xyz
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.gripdev.xyz
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: azureresources
    # singular name to be used as an alias on the CLI and for display
    singular: azureresource
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AzureResource
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - az
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: kube-azcon
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: kube-azcon
   spec:
     containers:
       – name: kube-azcon-controller
         image: lawrencegripper/kube-azcon
         env:
         - name: AZURE_CLIENT_ID
           value: 
         - name: AZURE_CLIENT_SECRET
           value: 
         - name: AZURE_RESOURCE_GROUP
           value: 
         - name: AZURE_SUBSCRIPTION_ID
           value: 
         - name: AZURE_TENANT_ID
           value: 
         - name: TEST_RESOURCE_PREFIX
           value: 
